### ISSUE TITLE
Enhancement: Use ErrorLevel.IGNORE for partials

### ISSUE THREAD

**Issue by tobymao** [pkit/sql-translate#2] opened 2023-05-16 23:38 UTC
When you're typing, you see errors because the sql is invalid. If you set the SQLGlot error level, perhaps you could be more lenient as I'm typing.

**Comment by pkit** [comment] 2023-05-17 02:22
Yup, nice idea. I have a lot more stuff coming up.

**Comment by pkit** [comment] 2023-05-19 15:19
@tobymao 
I have tried to reproduce it and it works as intended so far.
The typing is debounced while people type and only the final result is checked after 300ms of inactivity
Maybe more delay is needed?

**Comment by tobymao** [comment] 2023-05-19 15:26
sometimes people type slowly or have to think

**Comment by pkit** [comment] 2023-05-19 16:10
I'm not sure then, when errors should be checked?
1 sec on inactivity?
Or you would prefer a button?

**Comment by tobymao** [comment] 2023-05-19 16:38
what's wrong with the IGNORE? that way it doesn't matter if it's invalid

**Comment by pkit** [comment] 2023-05-19 16:41
Ignore just ignores errors, how user would know that the translated query is unusable?

**Comment by tobymao** [comment] 2023-05-19 16:46
maybe 300 ms is ignore, and 600 ms is not ignore

**Comment by pkit** [comment] 2023-05-19 17:44
Dunno if really closed it though, check it out and report, lol

**Closed as completed** 2023-05-19 17:44 UTC
